### PR TITLE
Add Faculty Glyphic + some improvements

### PR DESCRIPTION
**Pull request by emmamarichal**
Hello @DylanYoungKoto!

I'm Emma, I work with the Google Fonts team, and I'm assigned to Faculty Glyphic project. My role here is to add some improvement to the font so it can follow the GF specs (https://googlefonts.github.io/gf-guide/index).

You will find the detail of my modifications in the commits, but please feel free to ask if you have any questions.

______

I also so have some suggestions for the design: 

- The anchors position could be improved for the rounded letters:

Screenshot 2024-10-09 at 13 38 03

- Some segments have colinear vectors and some outlines contain any semi-vertical or semi-horizontal lines:
Screenshot 2024-10-09 at 13 34 54
Screenshot 2024-10-09 at 13 35 23

- I think the comma accent is a bit too small and light:
Screenshot 2024-10-09 at 13 39 24

___ 

Please, merge this PR **before** doing any modifications, to avoid any conflicts :) 

Cheers!

### CODE REVIEW

**Comment by DylanYoungKoto** [comment]
@emmamarichal 

Thank you for this feedback! I will make these updates ASAP. 

Sorry, i'm unfamiliar with Github, what do you mean by this: merge this PR before doing any modifications? 

Thanks!

**Comment by emmamarichal** [comment]
Hi @DylanYoungKoto, 

You should have a button with "Merge this Pull Request". It will allow to merge my changes to your current repo, so your modifications can be added to the file I already updated.

So, to sum up:
- You merge this Pull Request
- You will be able to do the update on the file I worked on
- You let me know when it's finished, so I can pull your work on my side, and re-export the font if necessary.

Please let me know if it's ok :)

Thank you!

**Comment by DylanYoungKoto** [comment]
@emmamarichal Thank you! I have made those changes and re-uploaded the packaged glyphs file and exported the font. Thank you for your help!

**Comment by emmamarichal** [comment]
@DylanYoungKoto Excellent! I'll take a look this week :)
Thanks!

**Pull request merged**
